apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: azureagentpools.devops.example.com
spec:
  group: devops.example.com
  names:
    kind: AzureAgentPool
    listKind: AzureAgentPoolList
    plural: azureagentpools
    singular: azureagentpool
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            poolName:
              type: string
          required:
          - poolName
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
